version: 2
orbs:
  codecov: codecov/codecov@1.0.4
jobs:
  build:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: 'npm install'
      - run: 'npm run build'
  test:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: 'npm install'
      - run: 'npm run build'
      - run: 'npm run test'
      - codecov/upload:
          file: coverage-final.json
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test